import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SupportedGames from "../components/home/supported-games"

const Home: NextPage = () => {
  return (
    <div className={styles.homePageContainer}>
      <Head>
        <title>Braket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SupportedGames />

    </div>
  )
}

export default Home
